ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - .gitignore
          - .releaserc.json
          - CODEOWNERS
          - renovate.json

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**.md'

src:
  - changed-files:
      - any-glob-to-any-file:
          - src/**
